import type { Metadata } from "next";
import "./globals.css";
import { Main } from "@/components/Main";

export const metadata: Metadata = {
  title: "Mkhotami Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </head>
      <body className={`font-nunito min-h-screen`}>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
